# Analysis commands

histograms:
	python find_mask_threshold.py

diagnostics:
	python findoutlier.py
	python graphoutlier.py
	python graph_lindiag_script.py
logistic:
	python logistic.py

smoothing:
	python make_smooth_graphs.py

glm:
	python regression_script.py

glmstandard:
	python regression_script_standard.py

heatmap:
	python plot_heatmap.py
	python plot_heatmap_standard.py

bncorrelates:
	python cross_subjects_linear_regression.py
	python neural_behavial_plot.py

mixedmodel:
	python lme_script.py
