# Analysis commands

histograms:
	python find_mask_threshold.py

diagnostics:
	python graph_lindiag_script.py
	python findoutlier.py
	python graphoutlier.py

logistic:
	python logistic.py

smoothing:
	python make_smooth_graphs.py

glm:
	python regression_script.py

glmstandard:
	python regression_script_standard.py

heatmap:
	python plot_heatmap.py
	python plot_heatmap_standard.py

mixedmodel:
	python lme_script.py
