# Analysis commands

histogram:
	python find_mask_threshold.py

diagnostics:
	python graph_lindiag_script.py
	python findoutlier.py
	python graphoutlier.py

logistic:
	python logistic.py

smoothing:
	python make_smooth_graphs.py

glm:
	python regression_script.py

mixedmodel:
	python lme_script.py
